/**
 * Dish catalogue for Mood Menu.
 *
 * Each entry declares:
 *   id       stable slug, used for the "don't repeat myself" rotation
 *   name     what shows up on the card
 *   blurb    one line describing the dish
 *   why      the reason this dish suits the moods it scores well on
 *   moods    mood id -> fit score, 0..3 (3 = this is the dish for that mood)
 *   minutes  realistic hands-on + wait time
 *   effort   0 = unwrap it, 1 = assemble, 2 = light cooking, 3 = real cooking
 *   size     "snack" or "meal"
 *   diet     tags the dish satisfies: vegetarian, vegan, glutenFree, dairyFree
 *   tags     free-form descriptors used for small scoring nudges
 */

export const MOODS = [
  { id: "stressed", label: "Stressed", hint: "wound tight, too much going on" },
  { id: "anxious", label: "Anxious", hint: "jittery, stomach in a knot" },
  { id: "low", label: "Low", hint: "flat, sad, heavy" },
  { id: "angry", label: "Angry", hint: "irritable, need to bite something" },
  { id: "drained", label: "Drained", hint: "no energy left in the tank" },
  { id: "foggy", label: "Foggy", hint: "can't focus, brain is mush" },
  { id: "restless", label: "Restless", hint: "bored, want something to happen" },
  { id: "queasy", label: "Queasy", hint: "off, delicate, maybe unwell" },
  { id: "celebratory", label: "Celebratory", hint: "something good happened" },
  { id: "lonely", label: "Lonely", hint: "want comfort, want home" },
];

export const DIETS = [
  { id: "vegetarian", label: "Vegetarian" },
  { id: "vegan", label: "Vegan" },
  { id: "glutenFree", label: "Gluten-free" },
  { id: "dairyFree", label: "Dairy-free" },
];

export const DISHES = [
  {
    id: "congee",
    name: "Rice congee with ginger and scallion",
    blurb: "Rice simmered soft in stock until it gives up entirely.",
    why: "Warm, bland in the good way, and it asks nothing of your stomach.",
    moods: { queasy: 3, drained: 2, low: 2, lonely: 2, stressed: 1 },
    minutes: 35,
    effort: 2,
    size: "meal",
    diet: ["vegetarian", "vegan", "glutenFree", "dairyFree"],
    tags: ["warm", "soft", "gentle"],
  },
  {
    id: "buttered-toast-egg",
    name: "Buttered toast with a jammy egg",
    blurb: "Six-and-a-half minute egg, good bread, flaky salt.",
    why: "Protein and warm carbs in under ten minutes, no decisions required.",
    moods: { drained: 3, low: 2, foggy: 2, queasy: 1, lonely: 2 },
    minutes: 9,
    effort: 1,
    size: "meal",
    diet: ["vegetarian"],
    tags: ["warm", "protein", "quick"],
  },
  {
    id: "miso-soup",
    name: "Miso soup with tofu and greens",
    blurb: "Hot broth, silky tofu, whatever leaf is in the fridge.",
    why: "Salty and hydrating — it settles you without sitting heavy.",
    moods: { anxious: 3, queasy: 3, stressed: 2, drained: 2, low: 1 },
    minutes: 10,
    effort: 1,
    size: "meal",
    diet: ["vegetarian", "vegan", "dairyFree"],
    tags: ["warm", "broth", "light"],
  },
  {
    id: "cacio-e-pepe",
    name: "Cacio e pepe",
    blurb: "Pasta, pecorino, an aggressive amount of black pepper.",
    why: "Three ingredients, fifteen minutes, tastes like a much bigger effort.",
    moods: { low: 3, lonely: 3, stressed: 2, drained: 1, celebratory: 1 },
    minutes: 18,
    effort: 2,
    size: "meal",
    diet: ["vegetarian"],
    tags: ["warm", "carbs", "comfort"],
  },
  {
    id: "kimchi-fried-rice",
    name: "Kimchi fried rice",
    blurb: "Cold rice, sour kimchi, a fried egg on top.",
    why: "Sharp and hot enough to cut through a bad mood, and it uses leftovers.",
    moods: { angry: 3, restless: 3, foggy: 2, drained: 2, low: 1 },
    minutes: 15,
    effort: 2,
    size: "meal",
    diet: ["vegetarian", "dairyFree"],
    tags: ["spicy", "warm", "leftovers"],
  },
  {
    id: "dan-dan",
    name: "Dan dan noodles",
    blurb: "Chili oil, sesame paste, noodles, plenty of scallion.",
    why: "Chili gives you something loud to focus on when you're spoiling for a fight.",
    moods: { angry: 3, restless: 3, celebratory: 1, foggy: 1 },
    minutes: 25,
    effort: 2,
    size: "meal",
    diet: ["dairyFree"],
    tags: ["spicy", "warm", "noodles"],
  },
  {
    id: "greek-yogurt-bowl",
    name: "Yogurt with honey, walnuts and fruit",
    blurb: "Thick yogurt, a spoon of honey, something crunchy.",
    why: "Protein and a little sugar without a sugar crash twenty minutes later.",
    moods: { foggy: 3, anxious: 2, drained: 2, queasy: 1, restless: 1 },
    minutes: 4,
    effort: 0,
    size: "snack",
    diet: ["vegetarian", "glutenFree"],
    tags: ["cold", "protein", "quick"],
  },
  {
    id: "oatmeal",
    name: "Oatmeal with brown sugar and salt",
    blurb: "Oats cooked in milk or water until they go creamy.",
    why: "Slow carbs that hold a steady line instead of spiking and dropping you.",
    moods: { anxious: 3, low: 2, drained: 2, queasy: 2, lonely: 2 },
    minutes: 10,
    effort: 1,
    size: "meal",
    diet: ["vegetarian"],
    tags: ["warm", "soft", "carbs"],
  },
  {
    id: "chicken-soup",
    name: "Chicken soup with noodles",
    blurb: "Stock, shredded chicken, noodles, far too much dill.",
    why: "The single most reliable thing to eat when you feel fragile.",
    moods: { queasy: 3, lonely: 3, low: 3, drained: 2, stressed: 2 },
    minutes: 40,
    effort: 3,
    size: "meal",
    diet: ["dairyFree"],
    tags: ["warm", "broth", "comfort"],
  },
  {
    id: "grilled-cheese-tomato",
    name: "Grilled cheese and tomato soup",
    blurb: "Crisp buttered bread, molten cheese, soup for dunking.",
    why: "Textbook comfort — warm, salty, and it takes both hands.",
    moods: { low: 3, lonely: 3, stressed: 2, drained: 2 },
    minutes: 20,
    effort: 2,
    size: "meal",
    diet: ["vegetarian"],
    tags: ["warm", "comfort", "cheese"],
  },
  {
    id: "avocado-toast",
    name: "Avocado toast with chili and lemon",
    blurb: "Mashed avocado, acid, heat, good salt.",
    why: "Fat and fibre keep you level, and it's ready before the kettle boils.",
    moods: { foggy: 2, drained: 2, restless: 1, anxious: 1 },
    minutes: 6,
    effort: 1,
    size: "snack",
    diet: ["vegetarian", "vegan", "dairyFree"],
    tags: ["quick", "fresh"],
  },
  {
    id: "dal",
    name: "Red lentil dal with rice",
    blurb: "Lentils cooked down with cumin, garlic and a hit of ghee or oil.",
    why: "Soft, warm and filling, and it reheats for three more days.",
    moods: { low: 2, lonely: 2, drained: 3, stressed: 2, queasy: 1 },
    minutes: 35,
    effort: 2,
    size: "meal",
    diet: ["vegetarian", "vegan", "glutenFree", "dairyFree"],
    tags: ["warm", "soft", "batch"],
  },
  {
    id: "roast-chicken-dinner",
    name: "Roast chicken with potatoes",
    blurb: "One bird, one pan, an hour you spend doing something else.",
    why: "The oven does the work while you decompress, and the house smells right.",
    moods: { celebratory: 3, lonely: 2, restless: 2, low: 1 },
    minutes: 80,
    effort: 3,
    size: "meal",
    diet: ["glutenFree", "dairyFree"],
    tags: ["warm", "project", "leftovers"],
  },
  {
    id: "steak-frites",
    name: "Steak and fries",
    blurb: "Hot pan, hard sear, salted fries, mustard.",
    why: "A dish that acknowledges something happened today.",
    moods: { celebratory: 3, angry: 2, drained: 1, restless: 1 },
    minutes: 30,
    effort: 3,
    size: "meal",
    diet: ["glutenFree"],
    tags: ["protein", "rich"],
  },
  {
    id: "cold-noodle-salad",
    name: "Cold sesame noodle salad",
    blurb: "Chilled noodles, cucumber, sesame dressing, herbs.",
    why: "Cool and crunchy when heat and heaviness would make things worse.",
    moods: { angry: 2, restless: 2, foggy: 2, stressed: 1 },
    minutes: 20,
    effort: 2,
    size: "meal",
    diet: ["vegetarian", "vegan", "dairyFree"],
    tags: ["cold", "fresh", "noodles"],
  },
  {
    id: "banana-peanut-butter",
    name: "Banana with peanut butter",
    blurb: "A banana. Peanut butter. That's the whole recipe.",
    why: "Zero decisions, zero cleanup, and it stops the shakes.",
    moods: { drained: 3, foggy: 3, anxious: 2, queasy: 2 },
    minutes: 2,
    effort: 0,
    size: "snack",
    diet: ["vegetarian", "vegan", "glutenFree", "dairyFree"],
    tags: ["quick", "protein"],
  },
  {
    id: "cheese-crackers-olives",
    name: "Cheese, crackers and olives",
    blurb: "A plate of salty things, arranged with minimal ceremony.",
    why: "Grazing beats cooking when you want food but not a project.",
    moods: { restless: 3, celebratory: 2, stressed: 2, lonely: 1 },
    minutes: 5,
    effort: 0,
    size: "snack",
    diet: ["vegetarian"],
    tags: ["cold", "salty", "graze"],
  },
  {
    id: "ginger-tea-toast",
    name: "Ginger tea and dry toast",
    blurb: "Fresh ginger steeped in hot water, plain toast alongside.",
    why: "When your stomach is negotiating, start small and warm.",
    moods: { queasy: 3, anxious: 2, drained: 1 },
    minutes: 8,
    effort: 1,
    size: "snack",
    diet: ["vegetarian", "vegan", "dairyFree"],
    tags: ["warm", "gentle", "hydrating"],
  },
  {
    id: "shakshuka",
    name: "Shakshuka",
    blurb: "Eggs poached in spiced tomato, bread for mopping.",
    why: "One pan, gently spicy, and it feels like you cooked properly.",
    moods: { low: 2, restless: 2, celebratory: 2, angry: 1, lonely: 2 },
    minutes: 30,
    effort: 2,
    size: "meal",
    diet: ["vegetarian", "glutenFree", "dairyFree"],
    tags: ["warm", "spicy", "protein"],
  },
  {
    id: "big-salad",
    name: "A genuinely big salad",
    blurb: "Greens, a grain, something roasted, a real dressing, nuts.",
    why: "Bright and crunchy — it wakes you up when everything feels grey and heavy.",
    moods: { foggy: 3, restless: 2, stressed: 1, low: 1 },
    minutes: 20,
    effort: 2,
    size: "meal",
    diet: ["vegetarian", "vegan", "glutenFree", "dairyFree"],
    tags: ["cold", "fresh", "crunch"],
  },
  {
    id: "dumplings",
    name: "Frozen dumplings, pan-fried",
    blurb: "Straight from the freezer, crisped in oil, black vinegar to dip.",
    why: "Fifteen minutes from freezer to plate and it still counts as dinner.",
    moods: { drained: 3, stressed: 3, lonely: 2, restless: 2 },
    minutes: 14,
    effort: 1,
    size: "meal",
    diet: ["dairyFree"],
    tags: ["warm", "freezer", "quick"],
  },
  {
    id: "popcorn",
    name: "Stovetop popcorn with butter and salt",
    blurb: "Kernels, a lid, three minutes of noise.",
    why: "Something to do with your hands and something loud to listen to.",
    moods: { restless: 3, anxious: 2, stressed: 2, angry: 1 },
    minutes: 6,
    effort: 1,
    size: "snack",
    diet: ["vegetarian", "glutenFree"],
    tags: ["salty", "crunch", "graze"],
  },
  {
    id: "smoothie",
    name: "Banana, berry and yogurt smoothie",
    blurb: "Frozen fruit, yogurt or oat milk, blitzed.",
    why: "Cold and easy to get down when chewing feels like too much.",
    moods: { queasy: 2, drained: 2, foggy: 2, anxious: 1 },
    minutes: 5,
    effort: 1,
    size: "snack",
    diet: ["vegetarian", "glutenFree"],
    tags: ["cold", "hydrating", "quick"],
  },
  {
    id: "pho",
    name: "Pho (or the nearest good takeout broth)",
    blurb: "Deep broth, rice noodles, a pile of herbs and lime.",
    why: "Hot broth and herbs do more for a rough day than almost anything else.",
    moods: { queasy: 3, low: 2, lonely: 3, drained: 2, stressed: 2 },
    minutes: 20,
    effort: 0,
    size: "meal",
    diet: ["dairyFree", "glutenFree"],
    tags: ["warm", "broth", "takeout"],
  },
  {
    id: "baked-potato",
    name: "Baked potato with butter and cheese",
    blurb: "One potato, one oven, one hour of not thinking about it.",
    why: "Almost no work, and the waiting is part of the point.",
    moods: { low: 2, lonely: 2, stressed: 2, drained: 2 },
    minutes: 65,
    effort: 1,
    size: "meal",
    diet: ["vegetarian", "glutenFree"],
    tags: ["warm", "comfort", "hands-off"],
  },
  {
    id: "tacos",
    name: "Tacos with quick pickled onion",
    blurb: "Warm tortillas, whatever filling, sharp pink onions on top.",
    why: "Assembly is fun, sharing is easy, and it scales to however many people showed up.",
    moods: { celebratory: 3, restless: 2, angry: 1, foggy: 1 },
    minutes: 30,
    effort: 2,
    size: "meal",
    diet: ["glutenFree", "dairyFree"],
    tags: ["sharing", "fresh"],
  },
  {
    id: "chocolate-orange",
    name: "Dark chocolate and an orange",
    blurb: "Two squares of good chocolate, one cold orange.",
    why: "A small, sharp, sweet full stop that isn't a whole dessert.",
    moods: { low: 2, stressed: 2, celebratory: 1, restless: 1 },
    minutes: 2,
    effort: 0,
    size: "snack",
    diet: ["vegetarian", "vegan", "glutenFree", "dairyFree"],
    tags: ["sweet", "cold", "quick"],
  },
  {
    id: "risotto",
    name: "Mushroom risotto",
    blurb: "Twenty minutes of stirring, and that's the whole appeal.",
    why: "Repetitive stirring is unusually good at emptying a crowded head.",
    moods: { stressed: 3, restless: 3, lonely: 2, celebratory: 1 },
    minutes: 45,
    effort: 3,
    size: "meal",
    diet: ["vegetarian", "glutenFree"],
    tags: ["warm", "project", "meditative"],
  },
  {
    id: "bean-soup",
    name: "White bean and greens soup",
    blurb: "Beans, stock, a parmesan rind if you have one, kale at the end.",
    why: "Cheap, filling, forgiving, and it makes enough for tomorrow.",
    moods: { drained: 2, low: 2, stressed: 2, lonely: 2, queasy: 1 },
    minutes: 35,
    effort: 2,
    size: "meal",
    diet: ["vegetarian", "glutenFree", "dairyFree"],
    tags: ["warm", "batch", "broth"],
  },
  {
    id: "pancakes",
    name: "Pancakes, any time of day",
    blurb: "Batter, butter, syrup, no regard for the clock.",
    why: "Breakfast food after dark is a small, cheap act of defiance.",
    moods: { low: 3, celebratory: 2, lonely: 2, restless: 2 },
    minutes: 25,
    effort: 2,
    size: "meal",
    diet: ["vegetarian"],
    tags: ["sweet", "warm", "comfort"],
  },
];
